server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    driver-class-name: com.mysql.cj.jdbc.Driver
    password:  123456
    username: root
mybatis:
  mapper-locations: classpath*:mapper/*.xml
